# Generated by Django 4.1.3 on 2022-11-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
